name: build
on:
  push:
    branches: [main]
env:
  APP_NAME: uw-ops-agent

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          # 拉取代码并构建
          source ~/.profile
          GIT_SERVER=${{gitea.server_url}}
          git clone -q ${GIT_SERVER%%://*}://gitea:${{gitea.token}}@${GIT_SERVER#*://}/${{gitea.repository}}.git .
          mvn clean package -U -Dmaven.test.skip=true
          # 上传ops-center项目，并出发ci构建
          cp -f target/ops-agent uw-ops-center/src/main/resources/public/agent/download/
          cd uw-ops-center
          git add src/main/resources/public/agent/download/ops-agent
          git commit -m "ops-agent ci auto build"
          git push origin main
          echo "ops-agent build success!"
