package uw.ops.agent.vo.cmd;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * This class is auto generated by tools.
 * 自动生成
 *
 * @author axeon
 * @since 2023-05-24
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class DockerPsCmd {

    /**
     * id
     */
    @JsonProperty("ID")
    private String ID;


    /**
     * 名字
     */
    @JsonProperty("Name")
    private String Name;

    /**
     * 镜像
     */
    @JsonProperty("Image")
    private String Image;

    /**
     * 执行的命令
     */
    @JsonProperty("Command")
    private String Command;

    /**
     * 创建时间。2023-03-27 14:37:43 +0800 CST
     */
    @JsonProperty("CreatedAt")
    private String CreatedAt;


    /**
     * 运行状态。running
     */
    @JsonProperty("State")
    private String State;

    /**
     * 启动时间。Up 5 weeks
     */
    @JsonProperty("Status")
    private String Status;


    /**
     * 挂载点。 /etc/localtime,/home/mysql3308/conf,/home/mysql3308/logs,/home/mysql3308/data
     */
    @JsonProperty("Mounts")
    private String Mounts;

    /**
     * 网络模式。host
     */
    @JsonProperty("Networks")
    private String Networks;

    /**
     * 端口。
     */
    @JsonProperty("Ports")
    private String Ports;

    @Override
    public String toString() {
        return new ToStringBuilder(this)
                .append("ID", ID)
                .append("Name", Name)
                .append("Image", Image)
                .append("Command", Command)
                .append("CreatedAt", CreatedAt)
                .append("State", State)
                .append("Status", Status)
                .append("Mounts", Mounts)
                .append("Networks", Networks)
                .append("Ports", Ports)
                .toString();
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public String getName() {
        return Name;
    }

    public void setName(String name) {
        Name = name;
    }

    public String getImage() {
        return Image;
    }

    public void setImage(String image) {
        Image = image;
    }

    public String getCommand() {
        return Command;
    }

    public void setCommand(String command) {
        Command = command;
    }

    public String getCreatedAt() {
        return CreatedAt;
    }

    public void setCreatedAt(String createdAt) {
        CreatedAt = createdAt;
    }

    public String getState() {
        return State;
    }

    public void setState(String state) {
        State = state;
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String status) {
        Status = status;
    }

    public String getMounts() {
        return Mounts;
    }

    public void setMounts(String mounts) {
        Mounts = mounts;
    }

    public String getNetworks() {
        return Networks;
    }

    public void setNetworks(String networks) {
        Networks = networks;
    }

    public String getPorts() {
        return Ports;
    }

    public void setPorts(String ports) {
        Ports = ports;
    }
}