package uw.ops.agent.vo.cmd;


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * This class is auto generated by tools.
 * 自动生成
 *
 * @author axeon
 * @since 2023-05-23
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class DockerStatsCmd {


    /**
     * containerId。b498b4f644be24e02b91d103fe611882cd6e3e5238fb17753d0de590f4483866
     */
    @JsonProperty("ID")
    private String ID;

    /**
     * 容器名。
     */
    @JsonProperty("Name")
    private String Name;


    /**
     * cpu占用率。1.11%
     */
    @JsonProperty("CPUPerc")
    private String CPUPerc;

    /**
     * 内存占用率。6.60%
     */
    @JsonProperty("MemPerc")
    private String MemPerc;

    /**
     * 内存已用/总数。4.114GiB / 62.33GiB
     */
    @JsonProperty("MemUsage")
    private String MemUsage;

    /**
     * 磁盘写/读数据。882MB / 433GB
     */
    @JsonProperty("BlockIO")
    private String BlockIO;

    /**
     * 网络读写。0B / 0B
     */
    @JsonProperty("NetIO")
    private String NetIO;

    /**
     * 线程数。154
     */
    @JsonProperty("PIDs")
    private String PIDs;

    @Override
    public String toString() {
        return new ToStringBuilder(this)
                .append("ID", ID)
                .append("Name", Name)
                .append("CPUPerc", CPUPerc)
                .append("MemPerc", MemPerc)
                .append("MemUsage", MemUsage)
                .append("BlockIO", BlockIO)
                .append("NetIO", NetIO)
                .append("PIDs", PIDs)
                .toString();
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public String getName() {
        return Name;
    }

    public void setName(String name) {
        Name = name;
    }

    public String getCPUPerc() {
        return CPUPerc;
    }

    public void setCPUPerc(String CPUPerc) {
        this.CPUPerc = CPUPerc;
    }

    public String getMemPerc() {
        return MemPerc;
    }

    public void setMemPerc(String memPerc) {
        MemPerc = memPerc;
    }

    public String getMemUsage() {
        return MemUsage;
    }

    public void setMemUsage(String memUsage) {
        MemUsage = memUsage;
    }

    public String getBlockIO() {
        return BlockIO;
    }

    public void setBlockIO(String blockIO) {
        BlockIO = blockIO;
    }

    public String getNetIO() {
        return NetIO;
    }

    public void setNetIO(String netIO) {
        NetIO = netIO;
    }

    public String getPIDs() {
        return PIDs;
    }

    public void setPIDs(String PIDs) {
        this.PIDs = PIDs;
    }
}